name: Build APK

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-levels: "34"
          build-tools: "34.0.0"
      
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "Properties created"
          cat local.properties
      
      - name: Build Debug APK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          cat local.properties
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: osu-injector.apk
          path: app/build/outputs/apk/debug/app-debug.apk